# -*- coding: utf-8 -*-
"""Historias de usuario HU-09 a HU-16 (fin de ITER-2 e ITER-3 activa)."""
from jira_lib import p, h, bullets
from jira_issues_b import hu_desc

ISSUES_C = [
    dict(id="HU-09", type="Story", epic=2, sprint=1, status="done", pts=3,
         prio="Medium", labels=["UI", "iter-2"], version=1, comments=[],
         summary="Menu principal y menu de pausa",
         desc=hu_desc(
             "Como jugador, quiero un menu principal y un menu de pausa para iniciar, pausar y salir del juego ordenadamente.",
             "RF-09: El sistema debera mostrar un menu principal (Iniciar/Salir) al arrancar y un menu de pausa (Reanudar/Reiniciar/Salir) al presionar Escape, deteniendo el tiempo de juego.",
             ["El juego inicia siempre en el menu principal.",
              "Escape pausa el juego y detiene temporizador y ansiedad.",
              "Desde pausa se puede reanudar, reiniciar o volver al menu principal."],
             "Prueba de navegacion completa entre los 3 estados de UI sin estados inconsistentes.")),
    dict(id="HU-10", type="Story", epic=2, sprint=1, status="done", pts=8,
         prio="Highest", labels=["nivel", "procedural", "iter-2"], version=1,
         comments=["Implementado con control de probabilidades y semillas; los fallos de keynote quedaron corregidos (ver commit Fix Generator)."],
         summary="Generacion procedural de niveles con semilla",
         desc=hu_desc(
             "Como jugador, quiero niveles generados proceduralmente para que cada partida sea distinta.",
             "RF-10: El sistema debera generar el nivel a partir de una semilla, garantizando siempre: conectividad total de salas, >= 1 sala segura inicial y spawn valido del jugador y del objeto clave.",
             ["La misma semilla produce exactamente el mismo nivel (reproducible).",
              "El 100% de las salas son alcanzables desde el spawn (sin secciones aisladas).",
              "El objeto clave nunca spawnea fuera del mapa ni dentro de geometria."],
             "Generar 50 niveles con semillas distintas: 50/50 completables; repetir 10 con semilla fija: 10/10 identicos.")),
    dict(id="HU-11", type="Story", epic=2, sprint=1, status="done", pts=3,
         prio="High", labels=["gameplay", "iter-2"], version=1, comments=[],
         summary="HUD: reloj, nivel de ansiedad y mision activa",
         desc=hu_desc(
             "Como jugador, quiero ver en el HUD el reloj, mi ansiedad y la mision actual para entender mi situacion sin abrir menus.",
             "RNF-01: El HUD debera actualizarse cada frame sin bajar el framerate por debajo de 60 FPS en el equipo de referencia; ocupara <= 15% del area de pantalla.",
             ["Reloj, barra de ansiedad y texto de mision siempre visibles.",
              "Actualizacion en tiempo real sin contratiempos.",
              "El HUD no tapa el centro de vision del jugador."],
             "Medicion con overlay de FPS durante 5 minutos de juego: minimo registrado >= 60 FPS.")),
    dict(id="HU-12", type="Story", epic=2, sprint=1, status="done", pts=5,
         prio="High", labels=["gameplay", "iter-2"], version=1, comments=[],
         summary="Sistema de misiones por nivel",
         desc=hu_desc(
             "Como jugador, quiero recibir misiones (encontrar objeto, activar mecanismo) para tener objetivos claros por nivel.",
             "RF-12: El sistema debera gestionar una lista de misiones por nivel con estados (activa/completada), mostrar la mision activa en el HUD y validar su cumplimiento por eventos de juego.",
             ["Solo una mision activa visible a la vez.",
              "Completar una mision actualiza el HUD e inicia la siguiente.",
              "Completar todas las misiones habilita la condicion de victoria del nivel."],
             "Prueba de integracion: nivel con 3 misiones encadenadas completadas en orden.")),
    dict(id="HU-13", type="Story", epic=2, sprint=1, status="done", pts=3,
         prio="Medium", labels=["UI", "iter-2"], version=1, comments=[],
         summary="Minimapa de orientacion",
         desc=hu_desc(
             "Como jugador, quiero un minimapa para orientarme en niveles grandes sin perder la tension.",
             "RF-13: El sistema debera mostrar un minimapa con la posicion del jugador actualizada en tiempo real, revelando solo las zonas ya visitadas.",
             ["La posicion del jugador se actualiza sin retraso perceptible.",
              "Las zonas no visitadas permanecen ocultas.",
              "El minimapa refleja el nivel procedural generado."],
             "Prueba comparando minimapa vs. nivel generado en 3 semillas distintas.")),
    dict(id="HU-14", type="Story", epic=2, sprint=2, status="progress", pts=5,
         prio="High", labels=["terror", "iter-3"], version=None,
         comments=["PhobiaTrigger implementado. En prueba: calibrando umbrales de ansiedad para no saturar al jugador."],
         summary="Triggers de fobia y eventos de terror scripteados",
         desc=hu_desc(
             "Como jugador, quiero eventos de terror (sonidos, luces que se apagan, apariciones) activados en momentos clave para asustarme.",
             "RF-14: El sistema debera disparar eventos de terror al entrar a zonas trigger o al superar umbrales de ansiedad, con cooldown >= 30 s entre eventos para evitar saturacion.",
             ["Cada trigger se dispara una unica vez o tras su cooldown.",
              "Los eventos combinan al menos 2 canales (audio + luz/visual).",
              "Los eventos no interrumpen la condicion de victoria/derrota."],
             "Prueba de caja negra: recorrido que activa los 3 tipos de trigger; registro de que ninguno se repite antes del cooldown.")),
    dict(id="HU-15", type="Story", epic=2, sprint=2, status="progress", pts=8,
         prio="Highest", labels=["IA", "terror", "iter-3"], version=None,
         comments=["Entidad con Seek basico funcionando (SeguirJugador.cs). Falta: que desista al entrar a zona segura y audio propio."],
         summary="Entidad que persigue al jugador con niveles altos de ansiedad",
         desc=hu_desc(
             "Como jugador, quiero que una entidad me persiga cuando mi ansiedad es maxima para temer las zonas oscuras.",
             "RF-15: Si la ansiedad supera el 90% durante >= 5 s, el sistema debera activar una entidad que persiga al jugador (Seek), desistiendo al entrar en una sala segura; el contacto produce derrota.",
             ["La entidad solo aparece con ansiedad >= 90% sostenida.",
              "La entidad desiste y desaparece al entrar a sala segura.",
              "El contacto con la entidad dispara la derrota con su pantalla."],
             "Prueba funcional: forzar ansiedad al 90%, medir tiempo de activacion (<= 1 s tras el sostenido) y verificar desistimiento.")),
    dict(id="HU-16", type="Story", epic=2, sprint=2, status="progress", pts=5,
         prio="High", labels=["nivel", "iter-3"], version=None,
         comments=["Progresion base lista (level progression del repo). Falta enlazar parametros de dificultad con numero de nivel."],
         summary="Progresion de niveles con dificultad escalada",
         desc=hu_desc(
             "Como jugador, quiero que cada nivel sea mas grande y oscuro que el anterior para sentir progresion.",
             "RF-16: El sistema debera escalar la dificultad por nivel incrementando tamano del mapa (>= +20% por nivel), reduciendo el tiempo disponible (>= -10%) y agregando >= 1 evento de terror adicional.",
             ["Nivel N+1 es verificablemente mayor que nivel N.",
              "El tiempo disponible disminuye segun la regla.",
              "Tras completar un nivel se desbloquea el siguiente con transicion."],
             "Prueba de regresion en niveles 1 a 3: medir tamano, tiempo y eventos por nivel.")),
]
